# Generated by Django 5.2.10 on 2026-01-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('admin', 'Admin'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
    ]
